name: Terraform Format Check

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  terraform-fmt:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.3.0

    - name: Run terraform fmt check
      run: terraform fmt -check -recursive
