name: Terraform Format

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  terraform-fmt:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.3.0

    - name: Run terraform fmt
      run: terraform fmt -recursive

    - name: Commit formatted files
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add .
        git commit -m "Automated Terraform formatting"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
