name: Terraform Format Check

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  terraform-fmt:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.3.0

    - name: Run terraform fmt
      run: terraform fmt -check -recursive

    - name: Set up Git
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        
    - name: Commit and Push formatted files
      run: |
        git add .
        git commit -m "Automated Terraform formatting"
        git push https://github.com/${{ github.repository }}.git HEAD:main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
